### ISSUE TITLE
Update ruby

### ISSUE THREAD

**Issue by g4s8** [zerocracy/datum#396]
Rultor's image was updated, new ruby version on rultor is `2.6.0`, new PR's won't be merged with rultor until ruby update.

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/396#issuecomment-468743870))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#396](https://github.com/zerocracy/datum/issues/396), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
done

**Comment by 0crat** [comment]
Job [#396](https://github.com/zerocracy/datum/issues/396) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#396](https://github.com/zerocracy/datum/issues/396) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
